### ISSUE TITLE
Possible minor bug in PowerSpectralDensity marker

### ISSUE THREAD

**Issue by Laouen** [nice-tools/nice#18]
@fraimondo is it possible that the tmin and tmax parameters of the PowerSpectralDensity class constructor should be forwarded to the base class BasePowerSpectralDensity constructor? 

Currently, they are set as None in the call to the super constructor, see the line referenced in the link: https://github.com/nice-tools/nice/blob/acf5dc941694fc72e6d2f01dfcb8117936e02503/nice/markers/spectral.py#L162

**Comment by fraimondo** [comment]
Indeed it looks like a bug in the code, although it is not. It just allow for weird user input that does not make any sense.

Here's what you see:

https://github.com/nice-tools/nice/blob/acf5dc941694fc72e6d2f01dfcb8117936e02503/nice/markers/spectral.py#L159-L163

But even with that, none of the computations are wrong, mainly because of 

1) the `PowerSpectralDensity` requires a `PowerSpectralDensityEstimator` to be passed on, and this are the `tmin` and `tmax` values that count.

2) The parameters `tmin` and `tmax` of the `PowerSpectralDensity` do not have any effect. Indeed they should not be there. Maybe they are because any `BaseMarker` must accept `tmin` and `tmax` as input.

For 1) this is how it's used:

``` Python
    base_psd = PowerSpectralDensityEstimator(
        psd_method='welch', tmin=None, tmax=0.6, fmin=1., fmax=45.,
        psd_params=psds_params, comment='default')
    f_list = [
        PowerSpectralDensity(estimator=base_psd, fmin=1., fmax=4.,
                             normalize=False, comment='delta'),
        PowerSpectralDensity(estimator=base_psd, fmin=1., fmax=4.,
                             normalize=True, comment='deltan'),
        PowerSpectralDensity(estimator=base_psd, fmin=4., fmax=8.,
                             normalize=False, comment='theta'),
        PowerSpectralDensity(estimator=base_psd, fmin=4., fmax=8.,
                             normalize=True, comment='thetan'),
        PowerSpectralDensity(estimator=base_psd, fmin=8., fmax=12.,
                             normalize=False, comment='alpha'),
        PowerSpectralDensity(estimator=base_psd, fmin=8., fmax=12.,
                             normalize=True, comment='alphan'),
        PowerSpectralDensity(estimator=base_psd, fmin=12., fmax=30.,
                             normalize=False, comment='beta'),
        PowerSpectralDensity(estimator=base_psd, fmin=12., fmax=30.,
                             normalize=True, comment='betan'),
        PowerSpectralDensity(estimator=base_psd, fmin=30., fmax=45.,
                             normalize=False, comment='gamma'),
        PowerSpectralDensity(estimator=base_psd, fmin=30., fmax=45.,
                             normalize=True, comment='gamman'),
    ]
```
For 2) this is from `PowerSpectralDensityEstimator`. It seems that we were testing for `tmin` and `tmax` and then realized
that it does not make any sense to do it, as they don't have any purpose on `PowerSpectralDensity`.

https://github.com/nice-tools/nice/blob/acf5dc941694fc72e6d2f01dfcb8117936e02503/nice/markers/spectral.py#L55-L70

As you can see, the `fmin` and `fmax` of the marker has to be within the range of the `fmin` and `fmax` of the estimator.

However, there is no enforced rule on `tmin` and `tmax`.

**Comment by Laouen** [comment]
Totally Agree, checking the code better I can see that the used tmin, tmax are those from the PowerSpectralDensityEstimator. 

I do think that either removing or adding a clear comment  (maybe with a link to this issue) should be there to avoid further confusion.
